# Generated by Django 5.2.7 on 2025-10-31 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flight', '0002_booking'),
    ]

    operations = [
        migrations.AddField(
            model_name='flight',
            name='travel_class',
            field=models.CharField(choices=[('Economy', 'Economy'), ('Premium Economy', 'Premium Economy'), ('Business', 'Business'), ('First Class', 'First Class')], default='Economy', max_length=20),
        ),
    ]
